version: '3.1'

services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo-addons:/mnt/extra-addons/UV_Projet
    networks:
      - odoo-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge